### ISSUE TITLE
Generated interfaces with references to other types in the same source are missing package identifier

### ISSUE THREAD

**Issue by palsivertsen** [vburenin/ifacemaker#12]
Given this example package:
```
package a

type Dummy struct{}
type A struct{}

func (a *A) Dummy() *Dummy { return nil }
```
When running: `ifacemaker -f a/a.go -s A -i Aer -p b -o b/b.go` I expect the file `b/b.go` to look like this:
```
package b

import "a"

type Aer interface {
	Dummy() *a.Dummy
}
```
But I get a file like this:
```
package b

type Aer interface {
	Dummy() *Dummy
}
```

**Comment by vburenin** [comment]
@palsivertsen thanks for the report. This is definitely can become an issue if the target package is different. Current design, is very simple, it doesn't track type tree. Extending it to that level requires significant time investment. I will take a look into it when I get a chance. Meanwhile, if it is critical for you, feel free to make needed changes.

**Comment by nkovacs** [comment]
Fixing this requires parsing the type declaration of Dummy, since that way ifacemaker can know that Dummy is a type declared in this package, and not a builtin, for example. But what if the type declaration isn't in the same file? So the fix for this would require always parsing all the files in the source package. This could be done automatically even if you only specify a single file.

I'm also affected by this, so I can take a shot at it.

**Comment by vburenin** [comment]
The goal was to generate interfaces for testing purposes only, since using it as a tool to maintain product interfaces may lead to poor interfaces design. Be careful.

**Comment by Antonboom** [comment]
+1 to this issue

**Comment by vburenin** [comment]
Антон, если есть время и желание, вполне можешь законтрибутить изменение :)
Мне сейчас, к сожалению, совсем не до этого проекта и точно будет не до
него пока generics не добавят.
Тулза выполняет свою задачу для которой был написана и пока без сторонней
помощи я не могу её расширять.

**Comment by erstam** [comment]
Facing the same issue, any progress on this?

**Comment by vburenin** [comment]
> Facing the same issue, any progress on this?

Unfortunately no. Would you like to contribute a change?

**Comment by erstam** [comment]
> Unfortunately no. Would you like to contribute a change?

I'm looking into it right now, but that's kinda of a deep dig...  I'll post again if I get anything to share, might take a while

**Comment by erstam** [comment]
I just opened a PR to attempt to fix this.

**Comment by erstam** [comment]
> The goal was to generate interfaces for testing purposes only, since using it as a tool to maintain product interfaces may lead to poor interfaces design. Be careful.

Now that I have a potential fix, I realize what you mean by that.  I am getting to a point where:

- I have a struct `MyStruct` defined in PkgA
- One method of this struct looks like this : `func (s MyStruct) SomeMethod(customType SomeCustomType)`
- Obviously, `SomeCustomType` is also declared in PkgA
- I use ifacemaker to generate an interface out of `MyStruct` and I put this interface in PkgB.
- In the interface declaration, the same method as above looks like this: `func (s MyStruct) SomeMethod(customType PkgA.SomeCustomType)`

So I have this interface which "requires" any implementor to know about, and import, PkgB AND PkgA, which is by the way another implementor of the interface!  Bad design ?  Most probably...

One way or another, ifacemaker is used for testing anyway, together with other tools (I use mockery).  I just wanted to stick to the principle that the package using an interface should define it, and not the implementor.  However I think here we should bypass this principle.

**Comment by erstam** [comment]
Just to complete my last comment.  In order to be more "legit", `SomeCustomType` would be better declared in PkgB.

Interface method declaration in PkgB would then be `func (s MyStruct) SomeMethod(customType SomeCustomType)`

Implementor method declaration in PkgA would then be `func (s MyStruct) SomeMethod(customType PkgB.SomeCustomType)`

And this is already covered by ifacemaker v1.1.0

Same comment for the `Dummy` struct of the original poster, it should be defined in package "b".
