### ISSUE TITLE
Source package not imported if interfaces placed in different package

### ISSUE THREAD

**Issue by kasvtv** [vburenin/ifacemaker#48]
If one generates an interface into a different package than the source package, e.g.:

```
ifacemaker -f ../bindings.go -s MyStruct -o i_mystruct.go -p interfaces -i IMyStruct
```

Then the generated code may be invalid if any of the method signatures contain custom types defined in the source package, e.g.: the generated code in the `interfaces` package references a custom type defined in the source package as `MyType` instead of importing from the source package and refering to it as `bindings.MyType`

**Comment by Skarlso** [comment]
Going to take a stab at this. :)

**Comment by Skarlso** [comment]
For the record, we will solve this by importing the source package as a `.` import.

**Comment by Skarlso** [comment]
Ok, so this isn't trivial because of trying to determine fully qualified package name including the module name so the import statement can be correct.

Because it's not trivial to get the mod file for a file, I've wrote a small utility to locate the mod file for a given file. If it doesn't exist we will add the source package, if it does exist we add the package including the parsed module path.

In any case we only do this if the target package doesn't equal the source package.

**Comment by vburenin** [comment]
guys, don't overdo things on your end. auto generation of interfaces is very dangerous, especially if it becomes the part of the shared libraries, it may lead to the broken interfaces for library users.

**Comment by Skarlso** [comment]
The single folder thing isn't really a problem either... Since you usually target a single folder or a single file anyways. Not recursively many folders. So it would work but requires a bit of user action. :)

**Comment by Skarlso** [comment]
I added an option that can be passed in for each package to add as an extra `.` import. This allows for a small change set. I also added a few formattings and module update.
